# =======
# Site settings
# =======
title:       Apache Cordova
description: Apache Cordova is a set of device APIs that allow a web mobile app developer to access native device function from JavaScript.
url:         "http://cordova.apache.org" # the base hostname & protocol
baseurl:     "" # the subpath of the site, e.g. /blog/
rss_path:    /feed.xml

repo:
    uri:    https://github.com/apache/cordova-docs/
    branch: cordova-website

# NOTE: defaults are configured in _defaults.yml, which is a generated file

# =======
# Build settings
# =======
source:      www
destination: public

keep_files:  ['.git', '.svn', 'docs', 'wiki-images', 'static', 'images', 'downloads']

lsi: false
safe: true
highlighter: pygments

markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

# exclude directories from the build
exclude:
    - static/css-src
    - docs/de
    - docs/es
    - docs/fr
    - docs/it
    - docs/ja
    - docs/ko
    - docs/pl
    - docs/ru
    - docs/sl
    - docs/zh
    - docs/en/1.5.0
    - docs/en/1.6.0
    - docs/en/1.6.1
    - docs/en/1.7.0
    - docs/en/1.8.0
    - docs/en/1.8.1
    - docs/en/1.9.0
    - docs/en/2.0.0
    - docs/en/2.1.0
    - docs/en/2.2.0
    - docs/en/2.3.0
    - docs/en/2.4.0
    - docs/en/2.5.0
    - docs/en/2.6.0
    - docs/en/2.7.0
    - docs/en/2.8.0
    - docs/en/2.9.0
    - docs/en/3.0.0
    - docs/en/3.1.0
    - docs/en/3.2.0
    - docs/en/3.3.0
    - docs/en/3.4.0
    - docs/en/3.5.0
    - docs/en/3.6.0
    - docs/en/4.0.0
    - docs/en/5.1.1
    #not excluding edge or 5.0.0 for english (testing purposes)
